/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parcial3;

/**
 *
 * @author perez
 */
public class Productos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        comboP = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        comboD = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        optIVA = new javax.swing.JCheckBox();
        optSinIVA = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblIVA = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));

        jPanel1.setPreferredSize(new java.awt.Dimension(394, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(394, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(20, 238));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(20, 238));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 157, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridLayout(3, 1));

        jPanel6.setLayout(new java.awt.GridLayout(1, 3));

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        comboP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Juegos", "Juguetes", "Productos" }));
        jPanel9.add(comboP);

        jPanel6.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        comboD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Descuento 10%", "Descuento 20%", "Sin descuento" }));
        jPanel10.add(comboD);

        jPanel6.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(2, 1));

        buttonGroup1.add(optIVA);
        optIVA.setText("Con IVA");
        jPanel11.add(optIVA);

        buttonGroup1.add(optSinIVA);
        optSinIVA.setSelected(true);
        optSinIVA.setText("Sin IVA");
        jPanel11.add(optSinIVA);

        jPanel6.add(jPanel11);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jPanel12.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Producto");
        jPanel12.add(jLabel1);

        jLabel2.setText("Descuento");
        jPanel12.add(jLabel2);

        jLabel3.setText("Con IVA o Sin IVA");
        jPanel12.add(jLabel3);

        jPanel7.add(jPanel12);

        jPanel13.setLayout(new java.awt.GridLayout(3, 1));
        jPanel13.add(lblProducto);
        jPanel13.add(lblDescuento);
        jPanel13.add(lblIVA);

        jPanel7.add(jPanel13);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(1, 3));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel8.add(btnCalcular);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel8.add(btnCerrar);
        jPanel8.add(lblTotal);

        jPanel5.add(jPanel8);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.hide();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        
        float juego = 500.00f;
        float juguete = 100.00f;
        float producto = 50.00f;
        float precio = 0.0f;
        float descuento = 0.0f;
        float precioT = 0.0f;
        float iva = 0.0f;
        
        String p = (String) comboP.getSelectedItem();
        String d = (String) comboD.getSelectedItem();
        
        if(optIVA.isSelected()){
            if(p.equals("Juegos")){
                iva = juego * 0.16f;
                precio = juego * 1.16f;
            }else if(p.equals("Juguetes")){
                iva = juguete * 0.16f;
                precio = juguete * 1.16f;
            }else if(p.equals("Productos")){
                iva = producto * 0.16f;
                precio = producto * 1.16f;
            }
        }else if(optSinIVA.isSelected()){
            if(p.equals("Juegos")){
                iva = 0;
                precio = juego;
            }else if(p.equals("Juguetes")){
                iva = 0;
                precio = juguete;
            }else if(p.equals("Productos")){
                iva = 0;
                precio = producto;
            }
        }
        
        if(d.equals("Descuento 10%")){
            descuento = precio * 0.1f;
            precioT = precio - descuento;
        }else if(d.equals("Descuento 20%")){
            descuento = precio * 0.2f;
            precioT = precio - descuento;
        }else if(d.equals("Sin descuento")){
            precioT = precio;
        }
        
        lblProducto.setText(Float.toString(precio));
        lblDescuento.setText(Float.toString(descuento));
        lblIVA.setText(Float.toString(iva));
        lblTotal.setText(Float.toString(precioT));
    }//GEN-LAST:event_btnCalcularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCerrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboD;
    private javax.swing.JComboBox<String> comboP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JCheckBox optIVA;
    private javax.swing.JCheckBox optSinIVA;
    // End of variables declaration//GEN-END:variables
}
