/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import javax.swing.JOptionPane;

/**
 *
 * @author perez
 */
public class Cajero extends javax.swing.JFrame {
    
    private float saldo = 150;
    boolean punto = false;
    
    /**
     * Creates new form Cajero
     */
    public Cajero() {
        initComponents();
        setLocationRelativeTo(null);
        lblSaldo.setText("$" + Float.toString(saldo));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblSaldo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        txtDepositar = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnDepositar = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        txtRetirar = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        btnRetirar = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 200));
        setMinimumSize(new java.awt.Dimension(400, 200));
        setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        lblSaldo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblSaldo.setText("$");
        jPanel1.add(lblSaldo);

        jTabbedPane1.addTab("Saldo", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);
        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_END);
        jPanel2.add(jPanel6, java.awt.BorderLayout.LINE_END);
        jPanel2.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setLayout(new java.awt.GridLayout(3, 2));

        jLabel2.setText("Cntidad a depositar");
        jPanel8.add(jLabel2);

        jPanel9.setLayout(new java.awt.GridLayout(1, 1));

        txtDepositar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepositarKeyTyped(evt);
            }
        });
        jPanel9.add(txtDepositar);

        jPanel8.add(jPanel9);
        jPanel8.add(jPanel10);
        jPanel8.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(1, 1));

        btnDepositar.setText("Depositar");
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });
        jPanel12.add(btnDepositar);

        jPanel8.add(jPanel12);
        jPanel8.add(jPanel13);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Deposito", jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel14, java.awt.BorderLayout.PAGE_START);
        jPanel3.add(jPanel15, java.awt.BorderLayout.PAGE_END);
        jPanel3.add(jPanel16, java.awt.BorderLayout.LINE_END);
        jPanel3.add(jPanel17, java.awt.BorderLayout.LINE_START);

        jPanel18.setLayout(new java.awt.GridLayout(3, 2));

        jLabel4.setText("Cantidad a retirar");
        jPanel18.add(jLabel4);

        jPanel19.setLayout(new java.awt.GridLayout(1, 1));

        txtRetirar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRetirarKeyTyped(evt);
            }
        });
        jPanel19.add(txtRetirar);

        jPanel18.add(jPanel19);
        jPanel18.add(jPanel20);
        jPanel18.add(jPanel21);

        jPanel22.setLayout(new java.awt.GridLayout(1, 1));

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel22.add(btnRetirar);

        jPanel18.add(jPanel22);
        jPanel18.add(jPanel23);

        jPanel3.add(jPanel18, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Retiro", jPanel3);

        getContentPane().add(jTabbedPane1);

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Cerrar Sesion");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepositarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepositarKeyTyped
        // TODO add your handling code here:
        int letra = evt.getKeyChar();
        System.out.println(letra);
        
        if((letra >= 48 && letra <= 57) || (letra == 46)){
            /*if(punto == true && (letra >= 48 && letra <= 57)){
            //if((Integer.toString(letra).equals(".") && txtDepositar.addContainerListener(".")){
                evt.consume();
            }
            if(letra == 46){
                punto = true;
            }*/
        }else{
            evt.consume();
        }
    }//GEN-LAST:event_txtDepositarKeyTyped

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        // TODO add your handling code here:
        String depositar = txtDepositar.getText();
        int p = depositar.indexOf(".");
        int p1 = depositar.indexOf(".", p+1);
        
        if(p1 != -1){
           depositar = depositar.substring(0,p1);
        }
        System.out.println(depositar);
        saldo = saldo + Float.parseFloat(depositar);
        lblSaldo.setText(Float.toString(saldo));
        JOptionPane.showMessageDialog(null, "Deposito exitoso");
        txtDepositar.setText("");
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void txtRetirarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRetirarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetirarKeyTyped

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        // TODO add your handling code here:
        String retiro = txtRetirar.getText();
        
        int p = retiro.indexOf(".");
        int p1 = retiro.indexOf(".", p+1);
        
        if(p1 != -1){
           retiro = retiro.substring(0,p1);
        }
        
        if (saldo >= Float.parseFloat(retiro)){
            saldo = saldo - Float.parseFloat(retiro);
            lblSaldo.setText(Float.toString(saldo));
            JOptionPane.showMessageDialog(null, "Retiro exitoso");
            txtRetirar.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Saldo insuficiente");
            txtRetirar.setText("");
        }
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cajero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cajero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtDepositar;
    private javax.swing.JTextField txtRetirar;
    // End of variables declaration//GEN-END:variables
}
